import { createServer } from "node:http";
import { createMetaAuthorizationUrl,exchangeMetaServerCode,MetaBrokerSessionStore,validateDesktopRedirectUri,validateBrokerPublicUrl } from "./meta-auth-broker-core";

const appId=process.env.META_APP_ID?.trim(),appSecret=process.env.META_APP_SECRET?.trim(),publicBaseUrl=process.env.META_BROKER_PUBLIC_URL?.trim(),clients=new Set((process.env.META_BROKER_CLIENT_IDS??"").split(",").map(v=>v.trim()).filter(Boolean));
if(!appId||!appSecret||!publicBaseUrl||!clients.size)throw new Error("META_APP_ID, META_APP_SECRET, META_BROKER_PUBLIC_URL, and META_BROKER_CLIENT_IDS are required.");
validateBrokerPublicUrl(publicBaseUrl);const store=new MetaBrokerSessionStore();
const config={appId,appSecret,publicBaseUrl,allowedClientIds:clients};
const json=(res:import("node:http").ServerResponse,status:number,body:unknown)=>{res.writeHead(status,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify(body));};
const server=createServer(async(req,res)=>{try{const url=new URL(req.url??"/",publicBaseUrl);
 if(req.method==="POST"&&url.pathname==="/meta/oauth/session"){let raw="";for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw) as {clientId?:string;state?:string;desktopRedirectUri?:string};if(!body.clientId||!clients.has(body.clientId)||!body.state||!body.desktopRedirectUri)return json(res,400,{error:"Invalid broker session request."});const desktopRedirectUri=validateDesktopRedirectUri(body.desktopRedirectUri);const session=store.create({clientId:body.clientId,state:body.state,desktopRedirectUri});return json(res,200,{sessionId:session.id,authorizationUrl:createMetaAuthorizationUrl(config,{sessionId:session.id,state:session.state})});}
 if(req.method==="GET"&&url.pathname==="/meta/oauth/callback"){const code=url.searchParams.get("code"),state=url.searchParams.get("state");if(!code||!state){res.writeHead(400);return res.end("Meta authorization was not completed.");}let matched:null|ReturnType<typeof store.get>=null;for(const id of [url.searchParams.get("session_id")??""]){if(id)matched=store.get(id);}if(!matched){res.writeHead(400);return res.end("Broker session is missing.");}if(matched.state!==state){res.writeHead(400);return res.end("Invalid OAuth state.");}store.complete(matched.id,code);const callback=new URL(matched.desktopRedirectUri);callback.searchParams.set("code",code);callback.searchParams.set("state",state);res.writeHead(302,{location:callback.toString(),"cache-control":"no-store"});return res.end();}
 if(req.method==="POST"&&url.pathname==="/meta/oauth/exchange"){let raw="";for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw) as {clientId?:string;sessionId?:string;state?:string};if(!body.clientId||!clients.has(body.clientId)||!body.sessionId||!body.state)return json(res,400,{error:"Invalid exchange request."});const session=store.consume(body.sessionId,body.state);if(session.clientId!==body.clientId)return json(res,400,{error:"Broker client mismatch."});const token=await exchangeMetaServerCode(config,session.code!);return json(res,200,token);}
 json(res,404,{error:"Not found."});
 }catch(error){json(res,400,{error:error instanceof Error?error.message:String(error)});}});
const port=Number(process.env.PORT||8080);server.listen(port,"0.0.0.0",()=>console.log(`Meta Auth Broker listening on :${port}`));
