import assert from "node:assert/strict";
import test from "node:test";
import { Pool } from "pg";
import { PostgresMetaBrokerAdapter } from "./meta-auth-broker-postgres";
import { TransactionalMetaBrokerSessionStore } from "./meta-auth-broker-transactional-store";

const databaseUrl=process.env.META_BROKER_TEST_DATABASE_URL;
test("postgres broker store is shared and atomically single-use",{skip:!databaseUrl},async()=>{const pool=new Pool({connectionString:databaseUrl});try{await pool.query("DROP TABLE IF EXISTS meta_broker_sessions");await pool.query("DROP TABLE IF EXISTS meta_broker_schema_migrations");const a1=new PostgresMetaBrokerAdapter(pool),a2=new PostgresMetaBrokerAdapter(pool);await a1.migrate();assert.equal(await a2.ready(),true);const s1=new TransactionalMetaBrokerSessionStore(a1,60_000),s2=new TransactionalMetaBrokerSessionStore(a2,60_000);const session=await s1.create({clientId:"desktop",state:"state",desktopRedirectUri:"http://127.0.0.1:54321/meta-broker-callback"});assert.equal((await s2.get(session.id))?.clientId,"desktop");await s2.complete(session.id,"meta-code");const results=await Promise.allSettled([s1.consume(session.id,"state"),s2.consume(session.id,"state")]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(results.filter(r=>r.status==="rejected").length,1);}finally{await pool.end();}});
test("postgres broker store expires sessions in the database",{skip:!databaseUrl},async()=>{const pool=new Pool({connectionString:databaseUrl});try{const adapter=new PostgresMetaBrokerAdapter(pool);await adapter.migrate();const store=new TransactionalMetaBrokerSessionStore(adapter,20);const session=await store.create({clientId:"desktop",state:"expiring",desktopRedirectUri:"http://127.0.0.1:54322/meta-broker-callback"});await new Promise(r=>setTimeout(r,40));assert.equal(await store.get(session.id),null);await adapter.cleanup();const found=await pool.query("SELECT id FROM meta_broker_sessions WHERE id=$1",[session.id]);assert.equal(found.rows.length,0);}finally{await pool.end();}});
