import { createServer } from "node:http";
import { createMetaAuthorizationUrl,decodeBrokerState,exchangeMetaServerCode,MetaBrokerSessionStore,validateDesktopRedirectUri,validateBrokerPublicUrl } from "./meta-auth-broker-core";
import { FileMetaBrokerSessionStore } from "./meta-auth-broker-file-store";
import { TransactionalMetaBrokerSessionStore } from "./meta-auth-broker-transactional-store";
import { PostgresMetaBrokerAdapter } from "./meta-auth-broker-postgres";
import { Pool } from "pg";
import { applyBrokerSecurityHeaders,BrokerRateLimiter,readBrokerJson,requestKey,safeBrokerError } from "./meta-auth-broker-http";

async function main(){
const appId=process.env.META_APP_ID?.trim(),appSecret=process.env.META_APP_SECRET?.trim(),publicBaseUrl=process.env.META_BROKER_PUBLIC_URL?.trim(),clients=new Set((process.env.META_BROKER_CLIENT_IDS??"").split(",").map(v=>v.trim()).filter(Boolean));
if(!appId||!appSecret||!publicBaseUrl||!clients.size)throw new Error("META_APP_ID, META_APP_SECRET, META_BROKER_PUBLIC_URL, and META_BROKER_CLIENT_IDS are required.");
validateBrokerPublicUrl(publicBaseUrl);const sessionFile=process.env.META_BROKER_SESSION_FILE?.trim(),databaseUrl=process.env.META_BROKER_DATABASE_URL?.trim(),multiInstance=process.env.META_BROKER_MULTI_INSTANCE==="true";let store:import("./meta-auth-broker-core").MetaBrokerSessionStoreContract;if(databaseUrl){const pool=new Pool({connectionString:databaseUrl,max:Number(process.env.META_BROKER_DB_POOL_MAX||10),ssl:process.env.META_BROKER_DB_SSL==="true"?{rejectUnauthorized:true}:undefined});const adapter=new PostgresMetaBrokerAdapter(pool);await adapter.migrate();await adapter.cleanup();store=new TransactionalMetaBrokerSessionStore(adapter);}else{if(multiInstance)throw new Error("META_BROKER_MULTI_INSTANCE requires META_BROKER_DATABASE_URL; local memory/file stores are intentionally refused.");store=sessionFile?new FileMetaBrokerSessionStore(sessionFile):new MetaBrokerSessionStore();}
const config={appId,appSecret,publicBaseUrl,allowedClientIds:clients};
const limiter=new BrokerRateLimiter(Number(process.env.META_BROKER_RATE_LIMIT||30),60_000);
const json=(res:import("node:http").ServerResponse,status:number,body:unknown)=>{applyBrokerSecurityHeaders(res);res.writeHead(status,{"content-type":"application/json"});res.end(JSON.stringify(body));};
const server=createServer(async(req,res)=>{applyBrokerSecurityHeaders(res);try{const url=new URL(req.url??"/",publicBaseUrl);if(req.method==="GET"&&url.pathname==="/healthz")return json(res,200,{ok:true});if(!limiter.allow(requestKey(req)))return json(res,429,{error:"Too many broker requests."});
 if(req.method==="POST"&&url.pathname==="/meta/oauth/session"){const body=await readBrokerJson<{clientId?:string;state?:string;desktopRedirectUri?:string}>(req);if(!body.clientId||!clients.has(body.clientId)||!body.state||!body.desktopRedirectUri)return json(res,400,{error:"Invalid broker session request."});const desktopRedirectUri=validateDesktopRedirectUri(body.desktopRedirectUri);const session=await store.create({clientId:body.clientId,state:body.state,desktopRedirectUri});return json(res,200,{sessionId:session.id,authorizationUrl:createMetaAuthorizationUrl(config,{sessionId:session.id,state:session.state})});}
 if(req.method==="GET"&&url.pathname==="/meta/oauth/callback"){const code=url.searchParams.get("code"),state=url.searchParams.get("state");if(!code||!state){res.writeHead(400);return res.end("Meta authorization was not completed.");}const decoded=decodeBrokerState(state),matched=await store.get(decoded.sessionId);if(!matched){res.writeHead(400);return res.end("Broker session is missing.");}if(matched.state!==decoded.state){res.writeHead(400);return res.end("Invalid OAuth state.");}await store.complete(matched.id,code);const callback=new URL(matched.desktopRedirectUri);callback.searchParams.set("code",code);callback.searchParams.set("state",matched.state);res.writeHead(302,{location:callback.toString(),"cache-control":"no-store"});return res.end();}
 if(req.method==="POST"&&url.pathname==="/meta/oauth/exchange"){const body=await readBrokerJson<{clientId?:string;sessionId?:string;state?:string}>(req);if(!body.clientId||!clients.has(body.clientId)||!body.sessionId||!body.state)return json(res,400,{error:"Invalid exchange request."});const session=await store.consume(body.sessionId,body.state);if(session.clientId!==body.clientId)return json(res,400,{error:"Broker client mismatch."});const token=await exchangeMetaServerCode(config,session.code!);return json(res,200,token);}
 json(res,404,{error:"Not found."});
 }catch(error){json(res,400,{error:safeBrokerError(error)});}});
const port=Number(process.env.PORT||8080);server.listen(port,"0.0.0.0",()=>console.log(`Meta Auth Broker listening on :${port}`));
}
void main().catch(error=>{console.error("Meta Auth Broker failed to start:",error instanceof Error?error.message:String(error));process.exitCode=1;});
